apiVersion: v1
kind: Service

metadata:
  name: shopease-service
  namespace: ecommerce

spec:
  selector:
    app: shopease

  type: NodePort

  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
